### ISSUE TITLE
Can't use index signature types in model with generics

### ISSUE THREAD

**Issue by jmyrland** [ctrlplusb/easy-peasy#189]
Related issue: https://github.com/ctrlplusb/easy-peasy/issues/117

I'm using `"easy-peasy": "2.3.0"` and `"typescript": "3.3.4000"`.

I have the following store, which produces a TS "error":
```ts
interface IMyStoreModel<T extends IMyInterface> {
  myMap: {
    [id: string]: T;
  };
  values: Select<IMyStoreModel<T>, Array<T>>;
}

const generateModel = <T extends IMyInterface>() => {
  const myStore: IMyStoreModel<T> = {
    myMap: {},
    values: select(state => 
      Object.keys(state.map)
        //                  👇 error
        .map(key => state.myMap[key])),
  }
  return myStore;
}
```

If I define `IMyStoreModel` without using generic types, the error disappears:
```ts
// works
interface IMyStoreModel {
  myMap: {
    [id: string]: IMyInterface;
  };
  values: Select<IMyStoreModel, Array<IMyInterface>>;
} 
```

I could also cast `state.myMap` to its correct type - but that gets quite ugly.

Here is the exact error message produced:
> (property) myMap: Compact<{ [K in (T extends Select<any, any> | Reducer<any, any> ? string : never) | (T extends Select<any, any> | Reducer<any, any> ? number : never) | Exclude<Exclude<...>, (T extends Select<...> | Reducer<...> ? string : never) | (T extends Select<...> | Reducer<...> ? number : never)> | Exclude<...>]: { [P in keyof Compact<...>]: Compact<...>[P]; }[K]; } & Compact<...>>
Element implicitly has an 'any' type because type 'Compact<{ [K in (T extends Select<any, any> | Reducer<any, any> ? string : never) | (T extends Select<any, any> | Reducer<any, any> ? number : never) | Exclude<Exclude<...>, (T extends Select<...> | Reducer<...> ? string : never) | (T extends Select<...> | Reducer<...> ? number : neve...' has no index signature.

**Comment by ctrlplusb** [comment]
Hey @jmyrland,

Can you try upgrade to the latest version of easy-peasy? I believe this is an older issue with the bundled definitions that has since been fixed 👍

It's a non-breaking upgrade so you should be fine. 😁

**Comment by ctrlplusb** [comment]
Oh wait! My bad you are on the latest version. 😅

Ummm, I'll review this asap. 👍

**Comment by jmyrland** [comment]
Yeah I saw your original issue and upgraded to 3.4.0. It's only an issue with generic types. Not a huge issue, and it's easy to work around. However, would love to see a fix for this 😁 

I started out using the `Map<key, value>` type, but this had sort of the same issues if I remember correctly. Is the Map type supported for state properties or do you see any issues with this approach ? 🤔

**Comment by ctrlplusb** [comment]
Phew, that was tricky as hell. It's so hard to isolate index signatures when mapping over types.  I added your case to the typescript test files and my fix appears to be working. I've published this an alpha fix for now. I would really appreciate if you could test them out and feedback. I'm particularly interested to hear if any regressions were introduced. I have a fairly decent set of tests for the typescript defs so hopefully not. 🤞

```
npm i easy-peasy@2.3.1-alpha.0
```

> I started out using the Map<key, value> type, but this had sort of the same issues if I remember correctly. Is the Map type supported for state properties or do you see any issues with this approach ? 

Yeah, I don't recommend that approach as it's not a JSON serialisable structure. You'll definitely want the pure object form. 👍

**Comment by jmyrland** [comment]
Wow, did not expect a resolution this quickly! Well done! 😁

I will give it the alpha a shot and let you know how it works out in my case. 

> Yeah, I don't recommend that approach as it's not a JSON serialisable structure. You'll definitely want the pure object form. 👍

Ah, as I suspected. I have seen this when I've modeled my stores with class instances. This might be a good thing to document in relation to "how to model stores" and advice to use serializable types 👍

**Comment by jmyrland** [comment]
Sweet! Installed the alpha just now - and the error is gone! 👌 And I don't have to type cast results with this change! 🎉 

My current build of the project is currently unstable (failing tests due to breaking changes) - so I don't know for certain if this change has any side effects - but as far as I can tell, it works as it should!

**Comment by ctrlplusb** [comment]
FYI, Typescript 4.5.1 released, and it doesn't like this fix. Gets caught in infinite inference resolutions. I'm gonna try and figure it out prior to it becoming full patch.

**Comment by jmyrland** [comment]
Oh, we're a few minors behind I see 😅 Hopefully there are no breaking changes...

Keep me posted and I will test it with the new version of TS as well 😄

**Comment by ctrlplusb** [comment]
No worries, TBH I have been sticking to `3.3.4000` as `>=3.4` have introduced performance regressions with definitions of libraries such as styled-components. :)

**Comment by ctrlplusb** [comment]
Hey @jmyrland, I've released a new version which I believe fixes this issue across all the most recent versions of TS. I would really appreciate it if you could use this version and feedback to me. I'll likely publish this to master if you give me a thumbs up.

```
npm i easy-peasy@2.3.1-alpha.1
```

**Comment by jmyrland** [comment]
Testing ATM - it seems that accessing the state is working, but setting the state is not. (TS 3.3.4000)

I have updated your test case to account for this as well:

```ts
interface IMyInterface {
  name: string;
}

interface IMyInterfaceMap<T extends IMyInterface> {
  [id: string]: T;
}

interface IMyStoreModel<T extends IMyInterface> {
  myMap: IMyInterfaceMap<T>;
  values: Select<IMyStoreModel<T>, Array<T>>;
  setState: Action<IMyStoreModel<T>, IMyInterfaceMap<T>>
}

const generateModel = <T extends IMyInterface>(): IMyStoreModel<T> => {
  return {
    myMap: {},
    values: select(state => {
      return Object.keys(state.myMap).map(key => state.myMap[key]);
    }),
    setState: action((state, newMap) => {
      // 👇 error
      state.myMap = newMap;
    })
  };
};

interface IMyExtendedInterface extends IMyInterface {
  extended: boolean;
}

const store = createStore(generateModel<IMyExtendedInterface>());

const foo = Object.values(store.getState().myMap);
foo[0].name = 'bob';
foo[0].extended = true;

store.getState().myMap['foo'] = { name: 'bob', extended: true };

store.getState().myMap['foo'].name + 'foo';
```

**Comment by jmyrland** [comment]
Also tried upgrading TS to `3.5.1` - but the issue is still present there 😢

**Comment by ctrlplusb** [comment]
Great thanks I will add this to the test cases 👍

**Comment by ctrlplusb** [comment]
@jmyrland - 3rd times a charm.

```
npm i easy-peasy@2.3.1-alpha.2
```

**Comment by jmyrland** [comment]
It seems to be working, but there is something wierd with selectors - it does not seem to be part of the `state` object? 🤔 

Updated testcase for you:
```ts
interface IMyInterface {
  name: string;
}

interface IMyInterfaceMap<T extends IMyInterface> {
  [id: string]: T;
}

interface IMyStoreModel<T extends IMyInterface> {
  myMap: IMyInterfaceMap<T>;
  values: Select<IMyStoreModel<T>, Array<T>>;
  names: Select<IMyStoreModel<T>, string>;
  setState: Action<IMyStoreModel<T>, IMyInterfaceMap<T>>
}

const generateModel = <T extends IMyInterface>(): IMyStoreModel<T> => {
  return {
    myMap: {},
    values: select(state => {
      return Object.keys(state.myMap).map(key => state.myMap[key]);
    }),
    names: select(state => {
      //           👇 error
      return state.something.map(x => x.name);
    }),
    setState: action((state, newMap) => {
      state.myMap = newMap;
    })
  };
};

interface IMyExtendedInterface extends IMyInterface {
  extended: boolean;
}

const store = createStore(generateModel<IMyExtendedInterface>());

const foo = Object.values(store.getState().myMap);
foo[0].name = 'bob';
foo[0].extended = true;

store.getState().myMap['foo'] = { name: 'bob', extended: true };

store.getState().myMap['foo'].name + 'foo';
```

Error:
> Property 'something' does not exist on type 'Compact<{ myMap: IMyInterfaceMap<T>; } & Compact<{} & {}>>'.

I'm guessing selectors is supposed to be part of the first `Compact`-thingy?

**Comment by ctrlplusb** [comment]
Hey @jmyrland 

I updated your case a bit to what I think you were trying to describe:

```typescript
/* eslint-disable */

import { createStore, select, Select, action, Action } from 'easy-peasy';

interface IMyInterface {
  name: string;
}

interface Person extends IMyInterface {}

interface IMyStoreModel<T extends IMyInterface> {
  myMap: Record<string, T>;
  setMyMap: Action<IMyStoreModel<T>, Record<string, T>>;
  values: Select<IMyStoreModel<T>, Array<T>>;
  names: Select<IMyStoreModel<T>, Array<string>>;
}

const generateModel = <T extends IMyInterface>(): IMyStoreModel<T> => {
  return {
    myMap: {},
    setMyMap: action((state, payload) => {
      state.myMap = payload;
    }),
    values: select(state => {
      return Object.keys(state.myMap).map(key => state.myMap[key]);
    }),
    names: select(state => state.values.map(x => name)),
  };
};

const store = createStore(generateModel<Person>());

const foo = Object.values(store.getState().myMap);
foo[0].name = 'bob';

store.getState().myMap = {
  foo: { name: 'bob' },
};

store.getState().values.map(x => x.name);

store.getState().myMap['foo'] = { name: 'bob' };

store.getState().myMap['foo'].name + 'foo';
```

Interestingly, this works in `typescript@3.5.1`, but not in `typescript@3.4.5` (and I am assuming you are still using `typescript@3.3.4000` - so it doesn't work in that version either).

**Comment by jmyrland** [comment]
Ah yes, I was a little too quick there 😓 

I meant the following select (almost the one you got)
```ts
// selector
names: select(state => state.values.map(x => x.name)),

// usage:
store.getState().names
```
So in my case I get an error for `values`, basically stating that this property does not exist on `state` (in the selector). We are still on  version `3.3.4000`.

We are using CRA, and it seems we are bound to a specific TS version. When I tried upgrading to `3.5.1`, I got some "unstable" warnings. It may be that 3.4.5 is supported - but I would have to test it.

**Comment by jmyrland** [comment]
Umm, it seems like I only get the error in my IDE - but running `npm start` produces no error.. 🤔 

I'll have to check this out some more to see if I can spot why this is happening.

**Comment by ctrlplusb** [comment]
```
npm i easy-peasy@2.3.1-alpha.3
```

Tested on `3.4.5` and `3.5.1`

🤞

**Comment by jmyrland** [comment]
Now it's working with `typescript@3.4.5`! 🎉 🎉 🎉 

No errors - no warnings, all good! 😄 And all test passing! Great job! 👍

**Comment by jmyrland** [comment]
also `easy-peasy@2.3.1-alpha.3` worked like a charm. Seems like there was some issues with `easy-peasy@2.3.1-alpha.2` - even got errors with `useStore` hooks. All kinks gone after upgrading to alpha 3 👍

**Comment by jmyrland** [comment]
It's also compatible with `typescript@3.3.4000` FYI

**Comment by ctrlplusb** [comment]
Thanks so much for helping me check this change!

**Comment by jmyrland** [comment]
My pleasure! Looking forward to the patch 👍
